server:
  port: 8080
#  servlet:
#    context-path: /api/v1

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:partner_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  config:
    import: classpath:urls.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false